# Generated by Django 4.1 on 2022-08-11 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(help_text='serial number of the drone', max_length=100, unique=True)),
                ('drone_model', models.CharField(choices=[('Lightweight', 'heightweight'), ('Middleweight', 'middleweight'), ('Cruiserweight', 'cruiserweight'), ('Heavyweight', 'heavyweight')], help_text='model of the drone', max_length=100)),
                ('weight_limit', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(500, 'The maximum weight that can be carried is 500g'), django.core.validators.MinValueValidator(1, 'The minimum weight to load a drone with is 1g')])),
                ('battery_capacity', models.PositiveIntegerField(default=100, help_text="Battery's current capacity. Ranges from 0% to 100%", validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('state', models.CharField(choices=[('IDLE', 'idle'), ('LOADING', 'loading'), ('LOADED', 'loaded'), ('DELIVERING', 'delivering'), ('DELIVERED', 'delivered'), ('RETURNING', 'returning')], default='IDLE', help_text='statof the dronr', max_length=20)),
            ],
        ),
    ]
