# Generated by Django 4.1 on 2022-08-11 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-_]+$', 'Allowed only letters, numbers, -, _')])),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('code', models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Allowed only upper case letters, underscore and numbers')])),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
